# Generated by Django 3.1.1 on 2021-02-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210202_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='blood_gp',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
