# Generated by Django 3.1.1 on 2021-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210202_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='details',
            field=models.BooleanField(default=False),
        ),
    ]
