# Generated by Django 3.1.1 on 2021-02-02 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210203_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_log',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='work_log',
            name='work_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work_log',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
