# Generated by Django 3.1.1 on 2021-02-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20210203_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_log',
            name='worked_on',
            field=models.CharField(default='_', max_length=200),
            preserve_default=False,
        ),
    ]
