# Generated by Django 3.1.1 on 2021-02-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_work_log_worked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_log',
            name='work_file',
            field=models.FileField(null=True, upload_to='workfiles/%Y/%m/%d'),
        ),
    ]
